### ISSUE TITLE
Epic: Circus UI

### ISSUE THREAD

**Issue by Uninen** [slipmatio/slipmatio#30]
```[tasklist]
### Tasks
- [x] Desktop UI frame
- [ ] Tablet UI frame
- [ ] Mobile UI frame
- [ ] Extra Widescreen UI frame
- [ ] Component: One host video mode
- [ ] Component: Two hosts video mode
- [ ] Component: Text chat
- [ ] Component: Private messages
- [ ] Component: Audio chat
- [ ] Component: Audio chat connect tab
- [ ] Component: Audio settings tab
- [ ] Component: Profile card
- [ ] Component: Settings tab
- [ ] Component: Info tab
- [ ] Component: User list
- [ ] Component: Admin / host screen
- [ ] Component: Requests
- [ ] Component: Tip modal
- [ ] Component: Share modal
- [ ] Functionality: HYPE UI
- [ ] Functionality: HYPE calculations
- [ ] Functionality: Exit event
```
